In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import csv

### Method 1 of importing a csv file (**The Traditional way**)

In [5]:
with open("/content/mtcars.csv","r") as some_random_name:
  r = csv.reader(some_random_name, delimiter=",")
  for car in r:
    print(car)

['model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']
['Mazda RX4', '21', '6', '160', '110', '3.9', '2.62', '16.46', '0', '1', '4', '4']
['Mazda RX4 Wag', '21', '6', '160', '110', '3.9', '2.875', '17.02', '0', '1', '4', '4']
['Datsun 710', '22.8', '4', '108', '93', '3.85', '2.32', '18.61', '1', '1', '4', '1']
['Hornet 4 Drive', '21.4', '6', '258', '110', '3.08', '3.215', '19.44', '1', '0', '3', '1']
['Hornet Sportabout', '18.7', '8', '360', '175', '3.15', '3.44', '17.02', '0', '0', '3', '2']
['Valiant', '18.1', '6', '225', '105', '2.76', '3.46', '20.22', '1', '0', '3', '1']
['Duster 360', '14.3', '8', '360', '245', '3.21', '3.57', '15.84', '0', '0', '3', '4']
['Merc 240D', '24.4', '4', '146.7', '62', '3.69', '3.19', '20', '1', '0', '4', '2']
['Merc 230', '22.8', '4', '140.8', '95', '3.92', '3.15', '22.9', '1', '0', '4', '2']
['Merc 280', '19.2', '6', '167.6', '123', '3.92', '3.44', '18.3', '1', '0', '4', '4']
['Merc 280C', '17.8', '6', '167.6', '123', '3.92', '3.44', '18.9', '1', '0', '4', '4']
['Merc 450SE', '16.4', '8', '275.8', '180', '3.07', '4.07', '17.4', '0', '0', '3', '3']
['Merc 450SL', '17.3', '8', '275.8', '180', '3.07', '3.73', '17.6', '0', '0', '3', '3']
['Merc 450SLC', '15.2', '8', '275.8', '180', '3.07', '3.78', '18', '0', '0', '3', '3']
['Cadillac Fleetwood', '10.4', '8', '472', '205', '2.93', '5.25', '17.98', '0', '0', '3', '4']
['Lincoln Continental', '10.4', '8', '460', '215', '3', '5.424', '17.82', '0', '0', '3', '4']
['Chrysler Imperial', '14.7', '8', '440', '230', '3.23', '5.345', '17.42', '0', '0', '3', '4']
['Fiat 128', '32.4', '4', '78.7', '66', '4.08', '2.2', '19.47', '1', '1', '4', '1']
['Honda Civic', '30.4', '4', '75.7', '52', '4.93', '1.615', '18.52', '1', '1', '4', '2']
['Toyota Corolla', '33.9', '4', '71.1', '65', '4.22', '1.835', '19.9', '1', '1', '4', '1']
['Toyota Corona', '21.5', '4', '120.1', '97', '3.7', '2.465', '20.01', '1', '0', '3', '1']
['Dodge Challenger', '15.5', '8', '318', '150', '2.76', '3.52', '16.87', '0', '0', '3', '2']
['AMC Javelin', '15.2', '8', '304', '150', '3.15', '3.435', '17.3', '0', '0', '3', '2']
['Camaro Z28', '13.3', '8', '350', '245', '3.73', '3.84', '15.41', '0', '0', '3', '4']
['Pontiac Firebird', '19.2', '8', '400', '175', '3.08', '3.845', '17.05', '0', '0', '3', '2']
['Fiat X1-9', '27.3', '4', '79', '66', '4.08', '1.935', '18.9', '1', '1', '4', '1']
['Porsche 914-2', '26', '4', '120.3', '91', '4.43', '2.14', '16.7', '0', '1', '5', '2']
['Lotus Europa', '30.4', '4', '95.1', '113', '3.77', '1.513', '16.9', '1', '1', '5', '2']
['Ford Pantera L', '15.8', '8', '351', '264', '4.22', '3.17', '14.5', '0', '1', '5', '4']
['Ferrari Dino', '19.7', '6', '145', '175', '3.62', '2.77', '15.5', '0', '1', '5', '6']
['Maserati Bora', '15', '8', '301', '335', '3.54', '3.57', '14.6', '0', '1', '5', '8']
['Volvo 142E', '21.4', '4', '121', '109', '4.11', '2.78', '18.6', '1', '1', '4', '2']

### Using inbuilt Pandas function(**read_csv**)

In [6]:
cars = pd.read_csv('/content/mtcars.csv')
cars.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [7]:
length = cars.shape[0]
# In this file, length = 32

### **DESC**

In [8]:
cars.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

### **Method 2**

In [ ]:
print(cars.count())
print(cars.mean())
print(cars.std())
print(cars.min())
print(cars.quantile())
print(cars.max())

### **Method 3**

In [27]:
for i in range(1, cars.shape[1]):
  s = 0.0
  x = cars.iloc[:, i].tolist()
  x_sum = sum(x)
  x_mean = x_sum / length
  for j in range(0, cars.shape[0]):
    s += ((x[j] - x_mean)**2)
  print(f"""
  {cars.columns.values[i]} :
  Count = {length}
  Mean = {x_mean}
  Minimum = {min(x)}
  Maximum = {max(x)}
  Standard Deviation = {(s / (length-1)) ** (0.5)}
  """)

  mpg :
  Count = 32
  Mean = 20.090624999999996
  Minimum = 10.4
  Maximum = 33.9
  Standard Deviation = 6.026948052089105


  cyl :
  Count = 32
  Mean = 6.1875
  Minimum = 4
  Maximum = 8
  Standard Deviation = 1.7859216469465444


  disp :
  Count = 32
  Mean = 230.72187500000004
  Minimum = 71.1
  Maximum = 472.0
  Standard Deviation = 123.93869383138194


  hp :
  Count = 32
  Mean = 146.6875
  Minimum = 52
  Maximum = 335
  Standard Deviation = 68.56286848932059


  drat :
  Count = 32
  Mean = 3.5965625000000006
  Minimum = 2.76
  Maximum = 4.93
  Standard Deviation = 0.5346787360709716


  wt :
  Count = 32
  Mean = 3.2172499999999995
  Minimum = 1.513
  Maximum = 5.424
  Standard Deviation = 0.9784574429896967


  qsec :
  Count = 32
  Mean = 17.848750000000003
  Minimum = 14.5
  Maximum = 22.9
  Standard Deviation = 1.7869432360968431


  vs :
  Count = 32
  Mean = 0.4375
  Minimum = 0
  Maximum = 1
  Standard Deviation = 0.5040161287741853


  am :
  Count = 32
  Mean = 0.40625
  Minimum = 0
  Maximum = 1
  Standard Deviation = 0.49899091723584604


  gear :
  Count = 32
  Mean = 3.6875
  Minimum = 3
  Maximum = 5
  Standard Deviation = 0.7378040652569471


  carb :
  Count = 32
  Mean = 2.8125
  Minimum = 1
  Maximum = 8
  Standard Deviation = 1.6151999776318522